### ISSUE TITLE
Rounding errors in product calculations

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#102]
We have issues where under certain circumstances a 0.00000000001 less of a product is being made.

All product values need to be rounded to the nearest 0.xxx of an integer, and stored as such to prevent these extremes of ever-so-slightly-off. 

The fallout of this is Satisfaction is showing 2000/2000 as unsatisfied and users are complaining that this is occuring.

Trimming and fixing productions appear to introduce the floats, not quite sure why it would but it is. There must be some wonky math going on, or the nature of working with floats, one of the two.

**Comment by Maelstromeous** [comment]
e.g.

```json
 {
      "id": "LiquidTurboFuel",
      "amount": 1666.65,
      "recipe": "Alternate_Turbofuel",
      "displayOrder": 5,
      "requirements": {
        "LiquidFuel": {
          "amount": 1999.98
        },
        "CompactedCoal": {
          "amount": 1333.3200000000002
        }
      },
      "buildingRequirements": {
        "name": "oilrefinery",
        "amount": 88.888,
        "powerPerBuilding": "6",
        "totalPower": 533.328
      },
      "byProducts": []
    }
```

**Comment by nils-keller-dev** [comment]
Is rounding to two decimal places a sufficient solution? Is it never expected to be more than that?

**Comment by samsmithnz** [comment]
That is a classic floating point issue - but I think it's ok. We just need to round when we do comparisons?

**Comment by Maelstromeous** [comment]
A lot of the problems are stemming from the fact that Products allow you to add e.g. 12.000000003, which is being introduced by Trim / Fix Production buttons. If we can force all calculations to be of a 0.xx then that would resolve many many issues. I'd probably say 3 decimals is the utterly highest limit, I'd even argue that in production and imports especially we should round to the nearest number.

**Comment by samsmithnz** [comment]
Allowing 3 decimal places sounds fair - That is what it rounds to when you enter more than 3 decimal places in Satisfactory too!

**Comment by Maelstromeous** [comment]
I'll take this on tomorrow, late here in the UK.

**Comment by samsmithnz** [comment]
I like how you say it's late, but you go to bed after me and I'm 5 hours earlier than you. 🫣😂

**Comment by Maelstromeous** [comment]
I may be slightly crazy ;)
