### ISSUE TITLE
User session expires every couple of minutes. Subsequent login attempts fail

### ISSUE THREAD

**Issue by LanceMaverick** [satisfactory-factories/application#103]
This is the error I see in the developer console when I try to log in after the session expires and I try to log in again:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.satisfactory-factories.app/validate-token. (Reason: CORS preflight response did not succeed). Status code: 429.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.satisfactory-factories.app/validate-token. (Reason: CORS request did not succeed). Status code: (null).

Error during token validation: TypeError: NetworkError when attempting to fetch resource. [default-4NXCVyQ_.js:1:3865](https://satisfactory-factories.app/assets/default-4NXCVyQ_.js)
XHROPTIONS
https://api.satisfactory-factories.app/login
CORS Preflight Did Not Succeed

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.satisfactory-factories.app/login. (Reason: CORS preflight response did not succeed). Status code: 429.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.satisfactory-factories.app/login. (Reason: CORS request did not succeed). Status code: (null).
```

The login will eventually work, but the most recent data is always lost. I assume this could be due to high traffic volume but I'm not sure why it causes the session to expire.

Browser: Firefox 132.0.2

**Comment by Maelstromeous** [comment]
Hi @LanceMaverick,

Could you advise me please when these requests were made? For most of this afternoon I had a network outage where the API is stored. Is the problem still occuring now?

**Comment by Maelstromeous** [comment]
Ah never mind I'm seeing it in production right now. We did implement some rate limiting recently, looks like it's too aggressive. I'll dial it back.

**Comment by Maelstromeous** [comment]
It's been dialled back, can you verify you end as well?

**Comment by Maelstromeous** [comment]
Never mind... it turns out my Cloudflare Tunnel was down. I'm going to add a monitor now to repeatedly ping me until it's back online....

**Comment by Maelstromeous** [comment]
The container now has been slapped on the bottom with a `--restart unless-stopped` so if it decides to be so nice to do an update and NOT RESTART ITSELF then it will. 

I don't see this being a problem any more @LanceMaverick , please re-open if you are encountering any issues.

**Comment by LanceMaverick** [comment]
I wasn't sure about opening a new ticket as I see several being worked on that seem to be related(https://github.com/satisfactory-factories/application/issues/103, https://github.com/satisfactory-factories/application/issues/104 and https://github.com/satisfactory-factories/application/issues/108) but as of the time I'm writing this the rate limiting seems to be back in force and worse than before. Particular operations seem to guarantee a session expiry, such as typing the name of a new factory. It's also very laggy when typing, maybe due to requests to the back end being made during typing to save the changes in real time which then get rate limited?
After this issue was closed yesterday I noticed a big improvement (session expiry happened about once an hour instead of once every few minutes. Now however it seems to be every few seconds. 
Cheers

**Comment by Maelstromeous** [comment]
@LanceMaverick The session timeouts should now be fixed. In terms of lag and performance, this is a problem when the planner approaches around 20+ factories simply because of all the calculations it has to do. It's something I'm aware of.

In terms of the backend, your data is synced to the API every 10 seconds after changes are made. It doesn't continue to do this unless it needs to, so that isn't the source of your lag.

Would I be accurate in assuming you have a massive plan?
