### ISSUE TITLE
Can't register user

### ISSUE THREAD

**Issue by ABlumrich** [satisfactory-factories/application#106]
Says can't fetch server / no connection

**Comment by Maelstromeous** [comment]
I just tested registering a user, not seeing this I'm afraid! Could you try again?

**Comment by ABlumrich** [comment]
Looks like the account was created when I first tried. Not sure why I got
the error message

**Comment by Maelstromeous** [comment]
Hopefully it was just a random blip :)

**Comment by ABlumrich** [comment]
Thanks
