### ISSUE TITLE
Imports are not being marked as invalid when dependant factory exports are no longer able to fulfil requests

### ISSUE THREAD

**Issue by shakawkaw** [satisfactory-factories/application#107]
I'm not sure why this is a problem. I've tried fidgeting with the numbers on things but it will not resolve. Factory "Copperhead" is in permanent red status. Hope i'm not missing something obvious and wasting your time.

https://satisfactory-factories.app/share/nutritious-adorable-businessperson

ROFL at the short-URL generator.

## Mael's edits

Repro Steps:

1. Create the following factories:
  - Copper Ingots @500/m
  - Wire (680) & Cables (300), import copper to meet demand
  - Stators (10) importing wire to meet demand (80)

This is a valid plan.

2. Increase **cables** @400. Wire internal demand will increase beyond production capabilities to 800.
3. BUG: Observe now how Stators has an invalid input. HOWEVER data still has the links remaining.
4. Increase stators to 20 and the wire import to 160
5. Wire satisfaction number has not changed. It should be 960 (800 internal demand + 160 from stators fac)

Here is the dependency data of the Wire fac, where Stators is still dependant, which is correct because the input still exists:

```json
"dependencies": {
    "requests": {
      "1086": [
        {
          "part": "Wire",
          "amount": 160
        }
      ]
    },
    "metrics": {
      "Wire": {
        "part": "Wire",
        "request": 160,
        "supply": 0,
        "isRequestSatisfied": false, <<< This is why the factory is red.
        "difference": -160
      }
    }
  },
  ```

So this bug of two parts:

## Exports display
Exports should be display requests REGARDLESS of surplus, right now if there is no surplus it does not display at all, meaning the `isRequestSatisfied` is causing the user frustration as the factory is red and they don't know why or how to fix it. They need to show IF there is a surplus OR there is an input for the product.

## Satisfaction calculation
It seems when we are in this state the dependency requirement portion of the satisfaction calculation utterly breaks. There is this warning in the console to suggest it, which is coming from `dependencies.ts`:
`calculateDependencyMetrics: Could not find a surplus for part Wire. Wire`

Also there's an additional bug with the imports display on the Stators factory where it is showing the numbers (presumably because now it's an invalid input factory). This should be resolved by #113.

**Comment by Maelstromeous** [comment]
Wire is being requested by Ficist Motors from Copperhead when there is no valid exports for it.

This is a bug, and you're not the only one who has created this scenario, so it's clear that we're not wiping invalid inputs when exports have been delete or exhausted properly.

**Comment by Maelstromeous** [comment]
> ROFL at the short-URL generator.

That one is a gem, I love some of the links it's making, it's one of my faviourite features I've added so far 😂

**Comment by Maelstromeous** [comment]
Added writeup of the issue. Took some brainpower that one did!

**Comment by Maelstromeous** [comment]
Upgraded to P1, it massively breaks the data model.

**Comment by Maelstromeous** [comment]
Code here: https://github.com/satisfactory-factories/application/blob/fde6b50ae909f0c8a4a419d105ca4dc347f81ad0/web/src/components/planner/PlannerFactoryImports.vue#L176
