### ISSUE TITLE
Expand Discord server

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#118]
I've just now created a Discord server: https://discord.gg/QHguR2Ja

Ideally this server should contain some channels:

- announcements
- general
- FAQ
- help (tickets maybe?)
- development (github feed)
- credits (thanks to contributors, artwork etc)

**Comment by Maelstromeous** [comment]
CC @samsmithnz @jeroenpol @nils-keller-dev

**Comment by samsmithnz** [comment]
Less channels is more, honestly. I'd start with 1-3 and add more as you need them.
