### ISSUE TITLE
Actions: Triage label is not being removed after priority assigned

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#131]
https://github.com/satisfactory-factories/application/issues/130

**Comment by Maelstromeous** [comment]
https://github.com/satisfactory-factories/application/pull/137

**Comment by Maelstromeous** [comment]
Still the case

**Comment by samsmithnz** [comment]
I had only implemented P1's. I'll update it to remove on P2 and P3's too. (Maybe I am the AI?) ;)
