### ISSUE TITLE
Imports: Factory names are replaced by an ID

### ISSUE THREAD

**Issue by dennis** [satisfactory-factories/application#132]
See picture

![image](https://github.com/user-attachments/assets/420127d4-71e8-4945-b0d8-01c0a7f4969a)

The factory dropdown shows (when clicked) "No data available".

Everything else is listed with factory names. Not sure what caused it. Tried login/logout but no difference. 

Tried with different browser (edge) that have never loaded the site. Same result after logging into my account (tntion).

**Comment by Maelstromeous** [comment]
@dennis can you give us a share link please?

**Comment by dennis** [comment]
> @dennis can you give us a share link please?

https://satisfactory-factories.app/share/absurd-modern-vegetable

**Comment by Maelstromeous** [comment]
Yeah that is certainly not ideal. It will take some time to unpick this, and I'm on with fixing a major bug with the syncing feature at the moment, so it may be tomorrow we get to take look at this unless another contributor is free to take it on.

**Comment by Maelstromeous** [comment]
@dennis could you recreate one of the factories (not clone, full recreate) and see if it still has the same issues?

**Comment by dennis** [comment]
Tested by deleting Basic Oil, expecting me to have problems because of missing plastic. But the app still shows that my factories get enough plastic (like if it wasn't deleted).

Then I added a new plastic-producing factory, but even if its listed as exporting some plastic, i can't select it for "import" (Created a factory making Circuit Board, but under the Satisfactory list, it lacks plastic. But I cannot satisfy this as it doesn't see the available plastic).

**Comment by Maelstromeous** [comment]
@dennis could you open a new planner (not browser) tab and from scratch try to create the factory? I'm trying to determine if this is a data issue or not.

**Comment by dennis** [comment]
@Maelstromeous I did a simple setup. Everything worked. 

In the main tab, I was exploring the features and ended up building a fairly complicated setup. I got 2-3 factories that is red, but doesnt seem to have an issue. So I think its the data. 

Initially when I worked on it, i didnt have an account. Only on the next day, I created one. Dont know if this might have triggered something.

I'll try to rebuild my factories in a new tab tonight (European time) and see if I can provide you with something more concrete

**Comment by Maelstromeous** [comment]
> Initially when I worked on it, i didnt have an account. Only on the next day, I created one. Dont know if this might have triggered something.

Creating an account does nothing other than backs up your data really, so this isn't the cause.

My belief is that somehow your data got corrupted. While it is not ideal, this is an alpha, such breakages are going to occur and are likely going to be fairly common until the project is more stable.

If upon recreating your setup in the first tab that it works in the second tab, I'll close this issue off, please let me know if that's the case.

**Comment by dennis** [comment]
It seems to work this time so far. Will reopen if it happens again.

**Comment by Maelstromeous** [comment]
Thanks for getting back to me, sorry it broke!
