### ISSUE TITLE
UNKNOWN PART: PlutoniumWaste, NuclearWaste

### ISSUE THREAD

**Issue by dennis** [satisfactory-factories/application#133]
Trying to produce "Ficsonium", results in a  *requires* "UNKNOWN PART PlutoniumWaste"
Similary "Plutonium Pellet" and "Non-Fissile Uranium" results in a **requires** "UNKNOWN PART NuclearWaste!"

**Comment by Maelstromeous** [comment]
@dennis Share link would be useful :)

**Comment by dennis** [comment]
> @dennis Share link would be useful :)

Sorry - didnt think of that. Was expecting you could use the username to look at the data.

**Comment by Maelstromeous** [comment]
I personally can look at both ways, other contributors cannot which is why I ask for shares :)

Thanks for this, we can look into why the game data is apparently not working for those items.
