### ISSUE TITLE
Cloned Factories are somehow linked - updating one, updates the other

### ISSUE THREAD

**Issue by samsmithnz** [satisfactory-factories/application#142]
https://satisfactory-factories.app/share/shaggy-faint-exabyte

If you load this and open Space Elevator Part 1 or Space Elevator Part 2 - and change an item, it changes in both factories.

**Comment by Maelstromeous** [comment]
Sounds like it's making a shallow copy rather than a deep one. Could have happened when I did the big refactor, it appears to have introduced some bugs.

Ideally we need to add tests to stop these regressions from happening again, the clone factory stuff has no tests at this time.

**Comment by Maelstromeous** [comment]
Weirdly I'm not seeing this in live... @samsmithnz can you double check again?

**Comment by Maelstromeous** [comment]
I looked at the share link and updated Cables on Space Elevator Parts 1 and it didn't update cables on 2?

**Comment by samsmithnz** [comment]
Try a new factory cloned from an existing one (maybe it doesn't happen from the share link). Out getting dinner and can't check right now...

**Comment by Maelstromeous** [comment]
Yep I see it, thanks!
