### ISSUE TITLE
UNKNOWN PART DissolvedSilica

### ISSUE THREAD

**Issue by LonelyDaoist** [satisfactory-factories/application#146]
Hello,
the app is showing UNKNOWN PART DissolvedSilica.
Here's the share link: https://satisfactory-factories.app/share/tangy-burly-holiday

cheers

**Comment by samsmithnz** [comment]
Today I leaned about a new product, Dissolved Silica! I'll resolve this in my current spike around nuclear waste, leaves, alien parts and now, dissolved silica.

**Comment by Maelstromeous** [comment]
How exotic!

**Comment by Maelstromeous** [comment]
Related: #93
