### ISSUE TITLE
Power usage for under clocked machines is not correct.

### ISSUE THREAD

**Issue by samsmithnz** [satisfactory-factories/application#154]
**Today, if a constructor is under-clocked to 50%, it consumes 2MW of power** (e.g 4MW * 50% = 2MW). 

> power usage = initial power usage x clock speed

This is an over-simplification, **the power usage in this scenario should be 1.6MW.** 

The reason is that it's not a linear relationship, [the formula, according to the official wiki](https://satisfactory.wiki.gg/wiki/Clock_speed) is: 

> Power usage = initial power usage x (clock speed / 100)<sup>1.321928</sup>

**Comment by Maelstromeous** [comment]
#11
