### ISSUE TITLE
Incorrect nuclear waste recipes

### ISSUE THREAD

**Issue by LonelyDaoist** [satisfactory-factories/application#158]
Hello,
I'm not sure if this is related to #140, but the recipes for uranium waste and plutonium waste are wrong, here's a share [link](https://satisfactory-factories.app/share/flat-bumpy-petabyte)

On the official wiki:
- 10/min uranium waste need 0.2/min uranium fuel rod + 240/min water
- 1/min plutonium waste needs 0.1/min plutonium fuel rod + 240/min water

However the app shows:
- 10/min uranium waste need 0.04/min uranium fuel rod + 48/min water
- 1/min plutonium waste needs 0.01/min plutonium fuel rod + 24/min water

I think you guys mixed up the output from a single burning and the rate per minute

Cheers

![image](https://github.com/user-attachments/assets/d93e323d-aa7e-40a3-85a5-a6609bd42608)

![image](https://github.com/user-attachments/assets/5821faf1-b951-4297-afd2-9f296bd6bb54)

**Comment by samsmithnz** [comment]
Sounds likely - I'll fix this. The waste is very unique in the recipes, since a Nuclear Power Plant is technically not a processing factory.
