### ISSUE TITLE
Automated Miner recipe is missing

### ISSUE THREAD

**Issue by AndrewThomasWill** [satisfactory-factories/application#160]
Not sure if it would be an enhancement or bug, but I'm currently not able to select this recipe.
It's an edge case, but I would like to include it in my Factores 😄

![image](https://github.com/user-attachments/assets/90c55b18-5477-423a-8993-136e3aa137e9)

**Comment by samsmithnz** [comment]
I got this - there is a problem with the recipe. I suspect because it's also produced in the workshop, we just dropped the item, breaking the recipe.
