### ISSUE TITLE
Crude Oil image has broken

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#170]
Was working yesterday, think it's the recent parser stuff we've been doing.

<img width="249" alt="Screenshot 2024-11-25 at 02 03 49" src="https://github.com/user-attachments/assets/4915bd7f-d47f-46c2-9046-612de259fc24">

**Comment by samsmithnz** [comment]
Nuclear Power Plant image is missing too. (although this never worked)
