### ISSUE TITLE
Products: Allow editable ingredients to scale production to meet ingredient supply

### ISSUE THREAD

**Issue by Reactor-UK** [satisfactory-factories/application#173]
![image111111111](https://github.com/user-attachments/assets/4b4d4322-3c10-4458-8ca9-24cb38dcbf0c)

I'm trying to maximise the nodes in my vacinity.

In the image (example) have 2 mk4 belts of Iron Ore (960 total), sent to a factory using the Pure Iron Ingot recipe. The suggestion being that the number displayed next to Requires, "Iron Ore: 960.08/min" be editable. This would in my case, save me from guessing what the output would be prior to making the factory or checking after the fact.

I was asked to add an entry on github. Apologies for the terrible wording and hope the suggestion makes sense.

**Comment by Maelstromeous** [comment]
Apologies @Reactor-UK I thought I responded to this. A fellow collaborator is picking this up and is making it so!
