### ISSUE TITLE
Performance starts to degrade in larger plans

### ISSUE THREAD

**Issue by 450Volts** [satisfactory-factories/application#174]
It is very noticeable after 10 -15 factories. Unusable after 40. Windows 11. Chrome.

# Mael's edits
- We should not be running `calculateFactories` when loading the plan. Loading the plan should literally just be loading the plan.
- When opening a share link, we again should not be running `calculateFactories`.
- When swapping tabs, we should not be running `calculateFactories`
- When editing factories that have no exports or imports, we should not be running calculations upon other factories, as they are not involved (exception to this may be power calculations and world resources)
- We should not be running `calculateFactories` on every single factory, we should only be running `calculateFactories` on factories that are linked to the one that has been updated.
- Deleting a factory makes `calculateFactories` run at least twice. It is running `setFactories` twice for some reason.
- Rearranging the factories calls `calculateFactories`, presumably because setFactories is called.

**Comment by samsmithnz** [comment]
I also noticed some performance lag when I created my 16 factory build. We need to do more analysis at scale - but transparently @450Volts, we have only started working with scale factories in the last couple of days.

**Comment by 450Volts** [comment]
> @450Volts can you offer a share link please?

This is the link generated from the share button in mobile. https://satisfactory-factories.app/share/happy-witty-byte

I find that text fields that force updates (Factory name, item numbers, etc.) are the one that lag.

**Comment by Maelstromeous** [comment]
Yeah the thing you're seeing in particular is the fact when you update the name it runs calculations on EVERYTHING. But, rather than making it just do the update when you press enter and call it a day we (us devs) need to look at why it's lagging so hard in the first place, as it also showing for when you swap tabs etc.

**Comment by Maelstromeous** [comment]
@450Volts  Changing the name no longer causes massive lag, we're looking into other areas of improvement.

**Comment by 450Volts** [comment]
Confirm! Works much better!

**Comment by Maelstromeous** [comment]
Just got this profile where within a large plan (~40 facs) I was updating the notes of a factory and it was delayed by at least a SECOND PER LETTER!

https://profiler.firefox.com/from-browser/calltree/?globalTrackOrder=201&hiddenGlobalTracks=0&hiddenLocalTracksByPid=7572-0w4&implementation=js&tabID=76&thread=o&v=10

Seems Vue is doing a lot of shit it doesn't need to be doing when doing simple operations as updating the notes view. Need to learn how to make it no propagate like this.
