### ISSUE TITLE
Represent fatal errors better to the user

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#179]
When the factory plan fails to load, the user is currently presented with a blank page.

In order to fix their data, it generally means they have to blow their local storage away. For the browser novice this is quite a hard thing to do.

Therefore we should present a "Ooops, your plan didn't load. Unfortunately you have to delete your data or restore it from a remote backup". 

Which then blows away the user's localstorage factoryTab and if they're logged in attempt to replace it with the data. If it fails again we need to show them that "Yeah sorry shits corrupted, you need to blow your data away, sorry"

![Screenshot 2024-11-25 at 15 12 18](https://github.com/user-attachments/assets/4133b8d9-f447-47cf-a82a-130be4714ebf)

**Comment by samsmithnz** [comment]
Can we add a button when this happens to reset their local storage in the context of this website?

**Comment by Maelstromeous** [comment]
That's exactly what I'm proposing
