### ISSUE TITLE
Various fluid recipes are incorrect

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#2]
Getting reports of various fluid recipes being incorrect. Need to do a full comparison of them in game and see the issues.

**Comment by Maelstromeous** [comment]
Provisional fix in https://github.com/Maelstromeous/satisfactory-factories/commit/63c083b2c91be73066bf3e700a90f464cd4254f5, needs confirm

**Comment by Maelstromeous** [comment]
Can confirm there's still bugs:

<img width="1104" alt="Screenshot 2024-11-17 at 15 34 15" src="https://github.com/user-attachments/assets/123a596d-b1bf-4d43-bf15-b5eed330a448">


![Screenshot 2024-11-17 at 15 34 26](https://github.com/user-attachments/assets/cb2a8267-60dc-45e1-95ce-9fcfb7a6ba85)

Requests for water is too high.

**Comment by Maelstromeous** [comment]
Or not... apparently I can't read the fact that water is a byproduct and was used internally... that's a visualisation issue akin to #18

**Comment by Maelstromeous** [comment]
Wrote a test to confirm this, and can confirm they are heavily broken.

**Comment by samsmithnz** [comment]
I don't see where this is broken. The AL example above appears to be working - with the exception of the byproducts - which is well documented in other issues.

**Comment by Maelstromeous** [comment]
If you're happy with the recent parser fixes and the template tests and there's no "exotic" fluid stuff we need to handle then happy to close it off. I would like to see some resting around e.g. Excited matter. 

Also gases?

**Comment by samsmithnz** [comment]
gases are simpler than they sound, they are liquids with no head-lift requirements.

**Comment by Maelstromeous** [comment]
Alright, I'll close this off for now then since our confidence has increased.
