### ISSUE TITLE
Some alt recipes have no power

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#216]
https://satisfactory-factories.app/share/disgusting-bad-jackal

@samsmithnz

**Comment by samsmithnz** [comment]
@Maelstromeous It is not the parsing/recipes - I see power for every one of these recipes. It appears to be something in the planner where it doesn't recalculate the power? If I change one quantity in the textbox, all of the power values appear.

**Comment by Maelstromeous** [comment]
Yeah I see that as well, and there's other issues with the plan it seems. I'll close this off for now.
