### ISSUE TITLE
Allow exporting of by products

### ISSUE THREAD

**Issue by Jaxon-teBoekhorst** [satisfactory-factories/application#223]
When designing a fuel factory with the diluted packaged fuel chain, there was a polymer resin byproduct, I wanted to use said polymer resin as an import to another factory creating plastic and rubber from it, But I could not find an option to export byproducts or to import another factories byproducts

**Comment by AndrewThomasWill** [comment]
Can you please share a link to your plan?
This works as expected in the current version

![Screenshot_20241128-022653](https://github.com/user-attachments/assets/04da3d74-e513-4f05-a1a9-e56bd54b5f5c)
![Screenshot_20241128-022616](https://github.com/user-attachments/assets/da502993-521f-419b-9c0d-cf2425190c9a)
![Screenshot_20241128-022542](https://github.com/user-attachments/assets/5df3bce0-066f-4e02-bc30-d726198f5537)
![Screenshot_20241128-022351](https://github.com/user-attachments/assets/83c048a0-f393-4c24-81a2-e0b1f662d081)
![Screenshot_20241128-022302](https://github.com/user-attachments/assets/f3da60c1-a4c7-41c6-8c15-8971dbfa4f8c)

**Comment by AndrewThomasWill** [comment]
Also, if you go to our [Discord](https://discord.com/invite/zge68PrGJ7) we have a "Planner-Help" channel that can help you figure out how to use the tool, instead of creating an Issue here in GitHub

**Comment by Jaxon-teBoekhorst** [comment]
I just tested it again and it worked, not sure what I did wrong, thanks for the help. I will consult the discord if I need help again
