### ISSUE TITLE
Feature request: Button to merge factories

### ISSUE THREAD

**Issue by shakawkaw** [satisfactory-factories/application#252]
Putting this in a user story format to ease adoption if accepted.

**Story**: 
As a Satisfactory player, I start in a small area and gradually expand. My first factories may be small and somewhat close together. As I expand, these factories may become a single factory. I would like to easily combine my smaller factories into larger factories without having to individually move all the products and redefine all the imports/exports across all my factories.

**Acceptance Criteria**:
**AC1**. A button is created next to the "copy factory" button for each factory 
**AC2**. When the button is clicked, the user is prompted to select the factory to merge with
**AC3**. The user must choose which factory name to keep for the merged factory
**AC3.1**. The factory being selected from the list should be the default new factory name (note: assumption is being made that the user is most often choosing to merge the smaller factory into the larger one)
**AC3.1**. A message is displayed encouraging the user to save an export of their current state so they can recover if they make a mistake
**AC4**. Given the second merging factory has been chosen, and a name is present in the "Merged Factory Name" field, when the user clicks "Complete Merge", then
- All products, imports, and exports from the non-surviving factory are migrated to the surviving factory
- All notes (if implemented, see issue #250 ) from the non-surviving factory should be appended to the notes of the surviving factory
- All other critical details (since i don't contribute, I don't know what other things have to be taken into account) are migrated from the non-surviving factory to the surviving factory

**AC5**. The non-surviving factory is removed from the list of factories
**AC6**. The screen is auto-scrolled so that the view of the surviving factory is displayed
**AC7**. Imports at other factories which originated from the non-surviving factory are updated so that they originate from the surviving factory
**AC8**. Any exports at the surviving factory that were being imported by the non-surviving factory are deleted as the importing factory no longer exists
**AC9**. Any imports at the surviving factory that originated at the non-surviving factory are deleted as the product is now produced internally

**Comment by Maelstromeous** [comment]
While the idea has some merit, getting this to work while maintaining all of the dependency links and associated math with it is extremely complicated. 

I appriciate the highly detailed write-up, wish all the suggestions came like this, but at the end of the day the use case is just too niche for it to warrant the very complex development time. As you've stated in your ACs, it is not a simple task, and it is high effort low reward scenario.

**Comment by Maelstromeous** [comment]
Added additional detail to my response.
