### ISSUE TITLE
Quantum Encoder & Particle Accellerator has no energy values

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#26]
https://github.com/Maelstromeous/satisfactory-factories/issues/18 It appears Quantum Encoder Power demands don't function, this is likely due to the scaling demands of the building, further research is needed.

If anyone knows where to find the formula for the ranges please let me know!

**Comment by samsmithnz** [comment]
Does this help? https://satisfactory.wiki.gg/wiki/Quantum_Encoder#Power_fluctuation

**Comment by Maelstromeous** [comment]
It does indeed thank you!

**Comment by Maelstromeous** [comment]
Yeah it's a very interesting challenge for sure. I believe that the power scales up in a fairly gradual way (at least for particle accelerators). Truth be told, I never actually got to that late in the game so I've never used them 😂 

Looks like there's a **lot** of fun oddities when it comes to overclocking them as well... https://satisfactory.wiki.gg/wiki/Particle_Accelerator

**Comment by samsmithnz** [comment]
We have to get you there! We should start a server. Really test your app! :)

**Comment by Maelstromeous** [comment]
Haha I'm nearly there in my play through, currently playing Factorio (aka cracktrio) with friends right now, but I'll get there 😆

**Comment by samsmithnz** [comment]
Alright - to solve this one we need a decision. 

I think we should use the average value as the power value. These are all recipe based - which is ok, this is where having the power in each recipe helps us. Nuclear Pasta for example has a power range of 500-1500MW. Therefore, I'm proposing we enter the 1000MW average as the power. 

Then, we add two new fields to the recipe to cover min and max power usage. In the building power, we would display that next to the power. E.g. for Nuclear Pasta, it would look like this:

`1000MW (500-1500MW range)`

In the factory total, it would also capture the min and max. We could also add a note about the number of power storage units needed to even out the power.

**Comment by Maelstromeous** [comment]
I concur with this approach. I've been snooping on Satisfactory Tools and how they do power calculations, turns out they use the average and maximum values. They list it like this (for 0.5/m nuclear pasta using one PA)
<img width="919" alt="Screenshot 2024-11-24 at 01 20 11" src="https://github.com/user-attachments/assets/16556380-8a62-4842-a5de-91545e9c9915">

I think as a good starting point we can create a Factory Template matching this exactly and then start adding in more complicated examples.
