### ISSUE TITLE
Add notes and task icons on both factory list and factory headers

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#261]
Would be great to show the user they have notes or an outstanding task available on factories.

# Factory list

Should show up on factory list similar to this:

![Screenshot 2024-12-07 at 20 11 00](https://github.com/user-attachments/assets/84181fb4-9b16-474e-9418-353e8c20ac3b)

Obviously not with a red square and T is a nice font awesome denoting a task and N being the same with a note instead.

# Factory header

![Screenshot 2024-12-07 at 20 13 19](https://github.com/user-attachments/assets/e13492ac-d336-49cb-986b-7025eecf318a)

They should be contained within chips which jump the user to the notes and task section which is at the bottom of the factory.

**Comment by ClubiNew** [comment]
Working on this in #263
