### ISSUE TITLE
Add "Fix Production" button near the Product

### ISSUE THREAD

**Issue by Danariel** [satisfactory-factories/application#27]
Hi, it would be great if you can add the "Fix Production" button
![image](https://github.com/user-attachments/assets/c9f89a8a-3a07-48d6-9baa-7590765cd9d6)
near the Product
![image](https://github.com/user-attachments/assets/1ee7ffb7-e347-4e15-ad35-7738913eb438)

It would be like what you already did with the Imports, that it says "Trim" or "Satisfy if the quantity is not enough or too much.
The feature already exists, but is not added in the Product rows

**Comment by Maelstromeous** [comment]
Yep great idea!
