### ISSUE TITLE
Imports not updating the source factory

### ISSUE THREAD

**Issue by samsmithnz** [satisfactory-factories/application#273]
1. Create a new factory, "factory 1", add the part Reinforced Iron Plate
2. Create a second new factory, "factory 2", add the parts Iron Plate and Screws. 
3. Back at "factory 1", import Iron Plate from "Factory 2". 
4. Click the satisfy or fix import buttons to correct the quantities in factory 1. Note that the quantities are now correct
5. Check the "factory 2" production. The quantities have not updated.

**Comment by merriry** [comment]
Came here to report this exact thing.

**Comment by Maelstromeous** [comment]
@merriry fyi this issue has now been fixed.
