### ISSUE TITLE
Rocket fuel is showing packaged version icon

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#278]
![firefox_ttvFghqWLQ](https://github.com/user-attachments/assets/d9089cfe-5052-4b60-baab-51d1e00f20cb)

Just needs the images flipping round I think

**Comment by samsmithnz** [comment]
The packaged and unpackaged are the same image in the data files. Same for Ionized Fuel. Where are these images sourced from? The images on the [wiki](https://satisfactory.wiki.gg/wiki/Rocket_Fuel) are different sizes.

**Comment by Maelstromeous** [comment]
As it says on the readme, I yoinked them from Greeny (ST creator). It could entirely be that the images are completely wrong and require replacement.
