### ISSUE TITLE
Power Generation not being displayed in Firefox

### ISSUE THREAD

**Issue by nomis14** [satisfactory-factories/application#289]
I use Floorp as my daily browser (Firefox Fork) and Power Generation doesnt get displayed. I checked this by making a Factory with Power Generation in Chrome and pasting over into Firefox. I also checked this with Opera and Edge. I also tried switching my User Agent to Chrome and disable my Ad Blocker but none of that worked. 
It probably has something to do with displaying it as the the Power GEenrator I tried to add in Firefox were present in Chrome. When i first opened it up in Chrome there were six empty Power Generators in the Factory I tried to add them to.
I dont know why I didnt zhnik of this first but i opened the Console and tada:
![grafik](https://github.com/user-attachments/assets/90734c15-760b-4dfd-8c1c-8e57862d715d)

Hopefully this helps

**Comment by immerrr** [comment]
@nomis14 can you try https://satisfactory-factories-git-fork-i-35edba-maelstromeous-projects.vercel.app/ ?

**Comment by nomis14** [comment]
@immerrr Yeah it works now. Thanks
