### ISSUE TITLE
Can't import the same (by)product from two different factories

### ISSUE THREAD

**Issue by meiergeorg** [satisfactory-factories/application#290]
Hello yall,
with version 2 i could simulate my blueprints by copying small factories and importing one after the other in the factory that uses their product. This doesn't seem to be possible any more with v3. First I thought, my factory data are corrupted. So I recreated everything but still could reproduce the problem, see screenshot.

![grafik](https://github.com/user-attachments/assets/c6cd0b98-472d-4dcd-abfd-8b1834cc386b)

I propose, that users can decide to import the same product from different factories. But maybe it is a bug.

The console shows the following error, although the products and byproducts of the factory 8611 are correctly stated in the json (enclosed):

```
calculatePartSupply - inputs: Output part is missing from input! 
Proxy { <target>: {…}, <handler>: {…} }
​<target>: Object { factoryId: 8611, outputPart: null, amount: 0 }
​​amount: 0
​​factoryId: 8611
​​outputPart: null
​​
```
[2024-12-15-satisfactory-factories.json](https://github.com/user-attachments/files/18140643/2024-12-15-satisfactory-factories.json)

I wanted to import heavy oil residue from all the plastic factories.

Thanks for your time, 
best regards
Zekonnd

**Comment by Maelstromeous** [comment]
@meiergeorg now shows up correctly:

![Screenshot 2024-12-16 at 22 30 21](https://github.com/user-attachments/assets/89ffe09c-fd50-4198-b968-8109856597d3)

**Comment by meiergeorg** [comment]
Yes, now it works fine. Thanks for the quick action! Now I can use the factories.app quite well.
