### ISSUE TITLE
Support multiple recipes in a single factory.

### ISSUE THREAD

**Issue by plathrop** [satisfactory-factories/application#304]
A factory can't use multiple different recipes for the same product, which makes it difficult to represent some production lines.

As an example I just built a small Circuit Boards factory.

1. 3 Refineries using the Rubber recipe, producing Heavy Oil Residue as a byproduct.
2. 2 Refineries using the Alt: Heavy Oil Residue recipe, producing Polymer Resin as a byproduct.
3. I use the Heavy Oil Residue to produce Petroleum Coke which, along with the Rubber will go into the Circuit Boards (Alt: Electrode Circuit Board recipe) and Fuel, which I burn off in generators.
4. I then use the Polymer Resin byproduct in a Refinery with the Alt: Residual Rubber recipe to produce additional Rubber, so I can consume the Resin.

Unfortunately I can't use the planner to represent step 4 here, as you can't produce the same product with two different recipes in the interface.

**Comment by Maelstromeous** [comment]
@plathrop it looks perfectly possible to me? https://satisfactory-factories.app/share/small-fluffy-answer

**Comment by plathrop** [comment]
_facepalm_

I should have tried closing and re-opening the browser before I reported. You're right it 100% works. My bad, sorry!

**Comment by Maelstromeous** [comment]
This further highlights the need for the site to inform the user to refresh as part of #166 so all good!
