### ISSUE TITLE
Add ability to add products by X number of buildings

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#34]
E.g. I want to add 24 constructors of iron plates, rather than having to get out a calculator to figure out the quantity.

**Comment by samsmithnz** [comment]
Do people play like this often? I always calculate the number of plates I need and then divide by the production.

**Comment by Maelstromeous** [comment]
Yeah when people use blueprints they often ratio it by that. For example I have a "Constructor tower" BP that has exactly 16 constructors, and many recipes ratio quite nicely by that, e.g. Wire at 480 = 16 constructors worth, iron ingots etc all ratio really nicely.
