### ISSUE TITLE
Power data errors

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#35]
![Screenshot 2024-11-17 at 10 25 24](https://github.com/user-attachments/assets/cced19db-53fd-495b-9bad-e98eed00749c)

**Comment by samsmithnz** [comment]
Investigating... 

I believe it's a rounding error in the parsing from `game_data.json`, Cast Screws aren't showing power either, and have a base power requirement of 0.2. Also noticing Steel pipes doesn't show a power if the quantity is low (e.g. 15). 
```
            "building": {
                "name": "constructormk1",
                "power": "0.2"
            },
```

**Comment by Maelstromeous** [comment]
So there is currently a bug with power for when <0.99 of a building is used, thats logged under #5 , however this is a slightly different issue where the recipe itself doesn't appear to be pulling in any power metrics.

But, in the game data there is a power defined:

```json
{
            "id": "Silica",
            "displayName": "Silica",
            "ingredients": [
                {
                    "part": "RawQuartz",
                    "amount": 3,
                    "perMin": 22.5
                }
            ],
            "products": [
                {
                    "part": "Silica",
                    "amount": 5,
                    "perMin": 37.5,
                    "isByProduct": false
                }
            ],
            "building": {
                "name": "constructormk1",
                "power": "0.8"
            },
            "isAlternate": false,
            "isFicsmas": false
        },
```

So I think the site is somehow using the wrong power values, or there's another bug with how power is calculated.

**Comment by samsmithnz** [comment]
In `FactoryInterface.ts`, the TotalPower is a string - shouldn't that be a number? https://copilot-workspace.githubnext.com/Maelstromeous/satisfactory-factories?shareId=32bea2f3-2dd1-42a6-92c3-476a87a56fd4

**Comment by samsmithnz** [comment]
Creating a PR to test. 🚀

**Comment by Maelstromeous** [comment]
Yeah it would be nice if that whole power thing can be cleaned up, I'm not overly happy with it but it "works", but clearly there's some form of bugs with it going on.

**Comment by samsmithnz** [comment]
Looking at it - I think I see the problem. Question: How to I run the unit tests?

**Comment by Maelstromeous** [comment]
I believe that's in the readme if not I need to add it but it's `pnpm test` under /web, there are no tests for other components at this time

**Comment by samsmithnz** [comment]
Thanks - very helpful. I can see a power issue there now and can fix it. Note that on Main one of the tests currently fails.

**Comment by Maelstromeous** [comment]
> Thanks - very helpful. I can see a power issue there now and can fix it. Note that on `main` one of the tests currently fails:
> 
> ```
>   ● products › addProductToFactory › should add a product to a factory
> 
>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: "IngotIron"
>     Received: "IronIngot"
> ```

Tests are now fixed in main.

**Comment by samsmithnz** [comment]
I'm pretty sure the logic is pretty sound - I think it's now related to the game-data. I've [made some good improvements](https://github.com/Maelstromeous/satisfactory-factories/pull/40) to make power a number instead of a string, and found a couple rounding issues. 

The actual power problem is a parsing issue I think - and might be better as a separate PR. 

[Silica](https://github.com/samsmithnz/satisfactory-factories/blob/4860570df0d04e7d68b35682951e529f3d2dc72a/parsing/gameData.json#L8635) for example, the power should be 4MW. 
```
        {
            "id": "Silica",
            "displayName": "Silica",
            "ingredients": [
                {
                    "part": "RawQuartz",
                    "amount": 3,
                    "perMin": 22.5
                }
            ],
            "products": [
                {
                    "part": "Silica",
                    "amount": 5,
                    "perMin": 37.5,
                    "isByProduct": false
                }
            ],
            "building": {
                "name": "constructormk1",
                "power": "0.8"
            },
```


[Cast Screws](https://github.com/samsmithnz/satisfactory-factories/blob/4860570df0d04e7d68b35682951e529f3d2dc72a/parsing/gameData.json#L1534) too, the power number should be 4MW:
```
        {
            "id": "Alternate_Screw",
            "displayName": "Alternate: Cast Screw",
            "ingredients": [
                {
                    "part": "IronIngot",
                    "amount": 5,
                    "perMin": 12.5
                }
            ],
            "products": [
                {
                    "part": "IronScrew",
                    "amount": 20,
                    "perMin": 50,
                    "isByProduct": false
                }
            ],
            "building": {
                "name": "constructormk1",
                "power": "0.2"
            },
            "isAlternate": true,
            "isFicsmas": false
        },
```

**Comment by Maelstromeous** [comment]
Good find! I'll take a look and see if I can fix the game data.

**Comment by Maelstromeous** [comment]
@samsmithnz how did you come to the conclusion it should be 4MW? Here's the calculation that the parser uses https://github.com/Maelstromeous/satisfactory-factories/blob/main/parsing/src/processor.ts#L190

**Comment by samsmithnz** [comment]
Maybe I'm misunderstanding the recipe power, but generally the recipes require exactly 1 construction building. So Silica, takes in 22.5 Raw Quartz and outputs 37.5 Silica, in one Constructor, for 4MW of power. Therefore - shouldn't the power in the recipe by 4MW?

**Comment by Maelstromeous** [comment]
So power calculations should be `number buildings required * base power e.g. 4MW` . I tried to simplify this by aggregating it into a "x power per run of this recipe" to ease the math a bit, perhaps it's the wrong approach, as overclocking in the future needs to be taken into account.

**Comment by Maelstromeous** [comment]
Very strange though how this is only affecting Silica, I'll look into it more.

**Comment by Maelstromeous** [comment]
Just checked, the part can only be made in a constructor (and workbench, which I filter out), so the base power will be always 4MW.

**Comment by samsmithnz** [comment]
> Very strange though how this is only affecting Silica, I'll look into it more.

I think it's affecting a large number of recipes, not just Silica and Cast Screws. Looking at the regular Screw recipe the power required is set to 1 - it should be 4. Quartz Crystal is 1.3333, should be 4. etc.

**Comment by Maelstromeous** [comment]
I'll do some more digging today. This might be quite a widespread problem, I'll need to pull in external verification from e.g. Satisfactory Tools and do a proper deep dive.

**Comment by samsmithnz** [comment]
The format the Satisfactory team used for the data doesn't help. I don't understand how that file makes sense to them.

**Comment by Maelstromeous** [comment]
Once you realise literally everything in the game is backed in a class it's fairly simple. I'm also 99% confident they have some sort of mapping file that generates the version we get that makes far more sense, otherwise it would be utter madness!

But yeah I built my own parser to make any form of sense of it, that alone took me about a week to make due to the complexity, and A LOT of copilot / ChatGPT with the regex it uses, I hate writing RegEx it makes my brain explode :')

**Comment by Maelstromeous** [comment]
Deffo a data error. Refinery showing as 45 Power per building in the app, wiki says it's 30MW.

**Comment by Maelstromeous** [comment]
Parser data for building data at least appears correct, could be power per cycle calculations.

**Comment by Maelstromeous** [comment]
Error is in the recipe data.

```json
{
            "id": "Plastic",
            "displayName": "Plastic",
            "ingredients": [
                {
                    "part": "LiquidOil",
                    "amount": 3,
                    "perMin": 30
                }
            ],
            "products": [
                {
                    "part": "Plastic",
                    "amount": 2,
                    "perMin": 20,
                    "isByProduct": false
                },
                {
                    "part": "HeavyOilResidue",
                    "amount": 1,
                    "perMin": 10,
                    "isByProduct": true
                }
            ],
            "building": {
                "name": "oilrefinery",
                "power": "45" <<< should be 30
            },
```

**Comment by Maelstromeous** [comment]
@samsmithnz you wanted to get stuck in the parser, here's the perfect introduction to it, now hunt that bug :D
