### ISSUE TITLE
When adding a part, before selecting the recipe, the total power NaN's

### ISSUE THREAD

**Issue by samsmithnz** [satisfactory-factories/application#55]
I'm not sure what the behavior should be here. Should the power ignore products without recipes and calculate what it knows?

![Image](https://github.com/user-attachments/assets/0127e391-0ad1-4cdb-9b10-5f3621ca5d51)

**Comment by Maelstromeous** [comment]
Yeah very related to #38. Not sure how this bug came to be, there should be code that if the recipe has not been chosen that various calculations are ignored.

**Comment by Maelstromeous** [comment]
It doesn't any more, even when a recipe is not selected.

<img width="1161" alt="Screenshot 2024-12-09 at 23 32 11" src="https://github.com/user-attachments/assets/66fd27a6-9eca-4fe9-b750-25c15fa9cf7f">
<img width="424" alt="Screenshot 2024-12-09 at 23 32 16" src="https://github.com/user-attachments/assets/ba6c6bff-4e82-41e6-9b0f-0fd13ed1e130">
