### ISSUE TITLE
create project board to help with Prioritization

### ISSUE THREAD

**Issue by samsmithnz** [satisfactory-factories/application#75]
Should we create a GitHub project to prioritize the work? I see the P1's and P2's already, just curious if it's good to have some default views so it's easier to see what the P1's are, what the bugs are, etc.

**Comment by samsmithnz** [comment]
You ok if I take it as a todo?

**Comment by Maelstromeous** [comment]
Sure go for it, if you need any permissions let me know. Also feel free to assign yourself issues you fancy taking on, so I don't come in and ruin your parade :D

**Comment by samsmithnz** [comment]
I definitely need you @Maelstromeous  to create the project for the repo - only people with owner access can create a new project.

**Comment by Maelstromeous** [comment]
I've created some boards. I am more and more leaning towards converting this repo into an Organisation so I can give you proper access rights over it. I might do that tomorrow.

**Comment by Maelstromeous** [comment]
@samsmithnz I went ahead and did it, you should now have full rights to create Projects for the organisation.

**Comment by samsmithnz** [comment]
Great! But now i get this error: 

```
Error: Although you appear to have the correct authorization credentials, the `satisfactory-factories` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/ - https://docs.github.com/rest/git/refs#create-a-reference
```

**Comment by samsmithnz** [comment]
troubleshooting - remembered I have owner access and should be able to solve. 👀

**Comment by Maelstromeous** [comment]
Yeah that was likely due to me moving the project around to a different organisation, you have god mode now so should be possible to fix :)
