### ISSUE TITLE
When user logs in and they have unsaved data locally, their local data is silently overwritten

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#77]
I'm pretty sure I added some code where if the user had local data that was edited after the remote data was saved it should flag it to the user but that appears not to be working.

If the user has local data that differs from the remote data, they must be prompted before it nukes their data, or get offered the opportunity to replace the remote data with it.

Ideally should show a modal with a simple comparison of number of factories (names) ideally) and a choice between one or the other.

**Comment by regnare** [comment]
I've been having issues logging in today. When I was able to login, I definitely lost progress (about 2 or 3 factories). And then to make matters worse, a few moments later I got a message saying my session had expired.

**Comment by Maelstromeous** [comment]
Yeah this afternoon my home had a major network outage followed by a smaller Cloudflare tunnel related outage which I didn't detect for some time after, I apologise for this. I host the API service on my NAS due to cost reasons primarily, unfortunately that does mean that syncing and shares are subject to the whims of my network.

I'm going to create an issue to better represent to people when the backend service is unavailable.

**Comment by regnare** [comment]
No worries, it's alpha so hiccups are to be expected. I just wanted to report that I was seeing the issue as well. Thanks!

**Comment by Maelstromeous** [comment]
Upgrading to P1 as this causes massive detriment to people.
