### ISSUE TITLE
Decimal places very long on Exports section

### ISSUE THREAD

**Issue by mynameisyogi** [satisfactory-factories/application#83]
You mentioned on reddit to post a screenshot if I still see any issues with the decimal places.  I just found one, screenshot attached.  The factory is making 468.33333 (I tried shorter decimal places, same behaviour).  
![Screenshot 2024-11-18 212637](https://github.com/user-attachments/assets/bc815763-c9cf-4c52-a624-1783c0cc4075)

**Comment by Maelstromeous** [comment]
@mynameisyogi  thanks for the report!
