### ISSUE TITLE
We could use `messagePack` here to compress the JSON.

### ISSUE THREAD

**Issue by samsmithnz** [satisfactory-factories/application#89]
Perhaps an enhancement, but we could use `messagePack` here to compress the JSON.  
> According to tests and comparisons, MessagePack can compress data by up to 50% compared to JSON. This means a 10,000 character JSON string could potentially be reduced to around 5,000 characters when using MessagePack.

_Originally posted by @samsmithnz in https://github.com/satisfactory-factories/application/pull/74#discussion_r1848278857_

**Comment by Maelstromeous** [comment]
Would do this in Backend only, accept a full fat JSON body from the web client then compress it at the API end and store it, and upon retreval uncompress it for the web client. Saves us having to do compression and decompression in different places.

Primary struggles with this will be the TypeScript typing of the `Buffer` type.

**Comment by samsmithnz** [comment]
Just for clarity- this is just compression for storage. I agree overall storage is cheap- but these are fairly large json docs, and if there is less data to transfer between the web server to the database, we would see response improvements.

**Comment by mnmr** [comment]
> Just for clarity- this is just compression for storage. I agree overall storage is cheap- but these are fairly large json docs, and if there is less data to transfer between the web server to the database, we would see response improvements.

MessagePack does not compress the data, it merely represents it in binary form. The savings will therefore mostly be the elimination of white-space and property names. If the goal is to reduce size then compression is much better. 

Also, JSON and MsgPack data compress to same size.

References: 
https://gist.github.com/maxpert/3116560
https://www.peterbe.com/plog/msgpack-vs-json-with-gzip

**Comment by Maelstromeous** [comment]
That explains the Buffers. On this basis, this idea won't work because of it's complexity versus the benefits, so I'm going to close this off. We could look at using compression in the future for storage, for now though it's not even a minor concern. Thanks for your insights @mnmr.
