### ISSUE TITLE
Fix missing parts

### ISSUE THREAD

**Issue by KageKeeper** [satisfactory-factories/application#93]
Hello. Whilst defining a Biofuel Factory I am unable to completely satisfy the factory because it does not know how to handle the ingredients for Biomass or Alien Protein. I have checked each, and the UNKNOWN PART is displaying for each.

![image](https://github.com/user-attachments/assets/6e7cb0dd-46da-4fd7-956a-280444808a3c)

**Comment by Maelstromeous** [comment]
Ah, leaves. Heh so since Leaves are not technically produced by anything they aren't in the game data we have extrapolated from the game. This is an edge case since leaves are manually collected, and in fairness 99% of people wouldn't even consider adding it to the tool to automate as it's incredibly manual form of doing power.

But early game I can see the need for this, so we will endevour to make it possible.

**Comment by samsmithnz** [comment]
I think it's a valid recipe and we should find a way to add it. It generally exists in the other tools. When I build my early factories, I have a small processing place for these items, and if you are going for the golden nut achievement, processing animal parts into DNA is important too. At the beginning, planning for that power is important - more so now that the biomass burners can accept belts and leaves + wood directly...

But also given it's an early phase recipe, it doesn't need to be high priority.

**Comment by Maelstromeous** [comment]
Yeah I subscribe to the fact it can be used as a means to plan the potential of the power. On that basis then ok lets endevour to add them in.

**Comment by samsmithnz** [comment]
Are their tests for parsing? I don't think there are right? How do I run parsing locally/in codespaces? `index.ts game-docs.json game-date.json`?

**Comment by Maelstromeous** [comment]
Oh you are a true mascarist if you wanna unpick the regex laden parser 😂 90% of it ChatGPT wrote so maybe Copilot would be right at home 😂 

Yeah you're right there are no tests, there really aught to be. It should be a fairly simply matter of just copying how web does it, introduce jest, basically copy the jest.config.js file as it's practicly the same. 

To run it locally you'd simply add the `pnpm test` command (again copy it from /web) which should be all you need to do really. Then you make `.spec.ts` files next to the file you're testing. It's not a strict requirement to do so, just a community standard.

Ideally, `parser.ts` needs refactoring and breaking apart more so it can be tested in chopped up units. Thankfully it's fairly functionality modular so should be reletively trivial to do so.

**Comment by samsmithnz** [comment]
Ok- I have a day off tomorrow, I might poke around. We should setup a discord too, to chat.
