### ISSUE TITLE
Feature Request: Export to Spreadsheet of choice

### ISSUE THREAD

**Issue by KageKeeper** [satisfactory-factories/application#94]
I enjoy utilizing a number of planning tools for Satisfactory. I would like to request an 'Export' button to be able to smoothly export either individual factories, or the entire build (all factories each in their own Tab, perhaps?) into a spreadsheet of choice.

**Comment by Maelstromeous** [comment]
Hi @KageKeeper ,

We could do this, but the use case is rather limited. We would have to come up with a form of data structure that Excel / Google Sheets is happy with (CSV), which could be completely arbitary and not fit for your purpose.

There's also a lot to consider in terms of what datapoints we pull out into CSV format. What kind of data would you want to see?

**Comment by KageKeeper** [comment]
Hmm. To be honest I had not given it that much thought. I see what you are saying, however. What I may be looking for could be, and likely would be, different from what another user would be looking for.

I think most of my desires to use a spreadsheet are handled with your app. You have done a really excellent job with it thus far. Perhaps just adding some sort of 'Summary' section that shows total total items produced/used (exported)/currently available (as opposed to scrolling through all current factories to see that data) would satisfy that itch.

**Comment by Maelstromeous** [comment]
A generalized Statistics Panel is a good idea yeah, please could you make an new issue to that effect?

**Comment by Maelstromeous** [comment]
Closing in favour of #101
