### ISSUE TITLE
"No Data Available" When trying to import from factory

### ISSUE THREAD

**Issue by shakawkaw** [satisfactory-factories/application#97]
First off, great tool. :) Thank you for spending time creating it and making it available.

Issue: When trying to import a product from a factory, i am seeing "No Data Available". This is happening for all factories. I deleted local cookies and forced download to try and clear out any corrupted data but the issue persists. Image included. Username shakawkaw.

![image](https://github.com/user-attachments/assets/41989723-a2d7-4037-aac2-35ff34a53fd3)

**Comment by Maelstromeous** [comment]
Thanks for your feedback @shakawkaw , means a lot!

As for this, could you create us an example factory and send in a link for it? There's a new "Share Plan" button at the top that should allow you to share that with us.

**Comment by Maelstromeous** [comment]
Btw the likely cause of this is factory `Iron Mountain` doesn't contain any products that have available exports to satisfy the demands of the factory shown here.

**Comment by shakawkaw** [comment]
I did try to share but...whoops! got the below message.

[image: image.png]

However, that is moot as I do see you are correct in that I do not have a
surplus available at the exporting factory. I recently "TRIM"med the
production based on my lowered needs and thought I still had more available.

From a workflow perspective this seems counter-intuitive to have as the
default behavior. If I am building a new factory that requires a part, and
I have other factories that produce that part, my first instinct is to
define what I want to build at the new factory, then declare where I want
to import the parts from, then go "fix production" at the exporting factory
to see how to beef up my supply chain. Now that I understand what this
message means, I can go fix my source production to have even 1 surplus,
import it to the new factory, then go fix production. It's just odd to
require this extra step of getting 1 surplus to "enable" exporting, then
being able to import a number higher than 1. Seems you should just be able
to import a number higher than zero just as easily.

Side note: While ideally the lack of available surplus wouldn't constrain
part selection at all, if you, the dev/s would like to keep this behavior,
it would be helpful and improve usability to replace the "No data
available" message with more descriptive language when possible, such as
"no surplus available for export", or in the case of adding a factory that
doesn't export any of the dependencies of your current factory, "factory
does not produce needed parts", etc.

Hey, maybe i'll even get off my lazy butt and try to contribute. :) Damn
adult responsibilities (and factory-building) always getting in the way...

**Comment by Maelstromeous** [comment]
Unfortunately your image didn't come through, they don't work with email replies.

I could perhaps make it so that when you are creating a new factory, you are able to still select a factory despite it not having enough surplus, which will mark it red anyway due to the increased demand. 

It would actually make the filtering logic simiplier too, as we have to do a lot of calculations to ascertain if the factory has surplus within the filter.

**Comment by shakawkaw** [comment]
Gotcha,

Basically, the message said unable to Share Plan, contact you at Github to
report the issue.

Thanks for accepting feedback and being responsive. :)

I will try to Share again later, though, as I have another issue to report,
this time i think it's a real one.

Cheers,

**Comment by Maelstromeous** [comment]
I'll close this off for now, if you do get issues with the new share feature do report it as a seperate issue :)
