### ISSUE TITLE
Actions: Add "Triage" label to all new issues

### ISSUE THREAD

**Issue by Maelstromeous** [satisfactory-factories/application#98]
When issues come in, someone has to triage them. It would be nice if there was a label attached to them so someone can have a look at it, and can be automated on the Projects board as well.

Ideally as well once a label other tran triage has been applied, it should also remove triage from it.

**Comment by samsmithnz** [comment]
I got half way through a job to tag issues correctly today, but work took over. I can add a "to-be-triaged" label to new issues to help with this?

**Comment by Maelstromeous** [comment]
As long as it's automated yeah that would help
